[package]
name = "DES"
version = "0.1.0"
authors = ["Muzuwi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.20"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 2
